export default new Map([
  ['01d', 'icon_qingtian'],
  ['01n', 'icon_qingtian'],
  ['02d', 'icon_yintian'],
  ['02n', 'icon_yintian'],
  ['03d', 'icon_yintian'],
  ['03n', 'icon_yintian'],
  ['04d', 'icon_duoyun'],
  ['04n', 'icon_duoyun'],
  // ['01d', 'clear sky'],
  // ['02d', 'few clouds'],
  // ['03d', 'scattered clouds'],
  // ['04d', 'broken clouds'],
  // ['09d', 'shower rain'],
  // ['10d', 'rain'],
  // ['11d', 'thunderstorm'],
  // ['13d', 'snow'],
  // ['50d', 'mist'],
  // ['01n', 'clear sky'],
  // ['02n', 'few clouds'],
  // ['03n', 'scattered clouds'],
  // ['04n', 'broken clouds'],
  // ['09n', 'shower rain'],
  // ['10n', 'rain'],
  // ['11n', 'thunderstorm'],
  // ['13n', 'snow'],
  // ['50n', 'mist']
])
