export default new Map([
  ['01d', 'icon_qingtian'],
  ['01n', 'icon_qingtian'],
  ['02d', 'icon_yintian'],
  ['02n', 'icon_yintian'],
  ['03d', 'icon_yintian'],
  ['03n', 'icon_yintian'],
  ['04d', 'icon_duoyun'],
  ['04n', 'icon_duoyun'],
  ['09d', 'icon_leizhenyu'],
  ['09n', 'icon_leizhenyu'],
  ['10d', 'icon_leizhenyu'],
  ['10n', 'icon_leizhenyu'],
  ['11d', 'icon_shachenbao'],
  ['11n', 'icon_shachenbao'],
  ['13d', 'icon_yujiaxue'],
  ['13n', 'icon_yujiaxue'],
  ['50d', 'icon_wu'],
  ['50n', 'icon_wu']
])
